theme: jekyll-theme-minimal # Ou outro tema de sua preferência
baseurl: "/jekyll-serif-theme/"
title: Portifólio de Projetos e Documentações Desenvolvidas # Título que aparece na aba do navegador
description: por Bianca Fusinato
