remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Portifólio de Projetos e Documentações Desenvolvidas # Título que aparece na aba do navegador
description: por Bianca Fusinato
